MPESA_CONSUMER_KEY: "k3AdFU55tf7PglmOoV4UbDUThpT06JTi55Xge7GyacGEEvd4"
MPESA_CONSUMER_SECRET: "JRCj4KJdQwz2A9LEO2SjctjQxqqjArgRFzweoG4NMl80lxLfS6OPG7xuSLAVU64T"
MPESA_SHORTCODE: "174379"
MPESA_PASSKEY: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
MPESA_INITIATOR_USERNAME: "testapi"
MPESA_INITIATOR_SECURITY_CREDENTIAL: "Safaricom999!*!"
CALLBACK_URL: "https://c358-102-0-7-26.ngrok-free.app"
REGISTER_API_URL: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
QUERY_URL: "https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query"
